/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


import Controller.ViewExpandedBookingController;

/**
 *
 * @author Dell
 */
public class BookingCardPanel extends javax.swing.JPanel {
    
    private ViewExpandedBookingController viewDetailController;
    
  


    /**
     * Creates new form BookingCardPanel
     */
  
    public BookingCardPanel() {
      
        initComponents();
     

    }
// extends
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookingIdField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkInLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        guestLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        readmore_button = new javax.swing.JLabel();

        setBackground(new java.awt.Color(48, 47, 47));
        setMaximumSize(new java.awt.Dimension(210, 240));
        setPreferredSize(new java.awt.Dimension(210, 240));

        jPanel1.setBackground(new java.awt.Color(72, 99, 127));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Booking Id : ");

        bookingIdField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bookingIdField.setEnabled(false);
        bookingIdField.setFocusable(false);
        bookingIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingIdFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bookingIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Room Type :");

        roomLabel.setForeground(new java.awt.Color(255, 255, 255));
        roomLabel.setText("room");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check-in Date :");

        checkInLabel.setForeground(new java.awt.Color(255, 255, 255));
        checkInLabel.setText("check-in");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Guest :");

        guestLabel.setForeground(new java.awt.Color(255, 255, 255));
        guestLabel.setText("guest no.");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price :");

        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("price");

        readmore_button.setForeground(new java.awt.Color(255, 255, 255));
        readmore_button.setText("<html><u>read more.</u></html>");
        readmore_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        readmore_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readmore_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkInLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceLabel)
                                    .addComponent(guestLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roomLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(readmore_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(roomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(checkInLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(guestLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(readmore_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookingIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingIdFieldActionPerformed

    private void readmore_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readmore_buttonMouseClicked
        // TODO add your handling code here:
        int bookingId = Integer.parseInt(bookingIdField.getText());
        viewDetailController.detailedBookingInfo(bookingId);
       
    }//GEN-LAST:event_readmore_buttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookingIdField;
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JLabel guestLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel readmore_button;
    private javax.swing.JLabel roomLabel;
    // End of variables declaration//GEN-END:variables
 
  
//getter and setter for bookingId
    public int getBookingId() {
        return Integer.parseInt(bookingIdField.getText());
    }
    public void setBookingId(int bookingId) {
       this.bookingIdField.setText(String.valueOf(bookingId));
    }
    
    //getter and setter for roomType
    public String getRoomType() {
        return roomLabel.getText();
    }
    public void setRoomType(String roomType) {
        this.roomLabel.setText(roomType);
    }
    
    //getter and setter for checkInDate
    public String getCheckInDate() {
        return checkInLabel.getText();
    }
    public void setCheckInDate(String checkInDate) {
        this.checkInLabel.setText(checkInDate);
    }
    
    //getter and setter for guest count
    
    public int getGuestCount() {
        return Integer.parseInt(guestLabel.getText());
    }    
    public void setGuestCount(int price) {
        this.guestLabel.setText(String.valueOf(price));
    }
    
    //getter and setter for price
    public int getPrice() {
        return Integer.parseInt(priceLabel.getText());
    }    
    public void setPrice(String price) {
        this.priceLabel.setText(price);
    }
    public void setController(ViewExpandedBookingController controller) {
        this.viewDetailController = controller;
    }

    
  
}